server:
  port: 8090

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&failOverReadOnly=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
#      password: jiahao1851
      password: jiahao
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,log4j,config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #  redis:
  #    #数据库索引
  #    database: 1
  #    host: 120.78.206.25
  #    port: 30078
  #    password: WBarz6dLS96FtUSA
  #    jedis:
  #      pool:
  #        #最大连接数
  #        max-active: 8
  #        #最大阻塞等待时间(负数表示没限制)
  #        max-wait: 3000
  #        #最大空闲
  #        max-idle: 8
  #        #最小空闲
  #        min-idle: 0
  #    #连接超时时间
  #    timeout: 10000
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
mapper:
  mappers:
    - com.jiahao.per_demo.config.mapper.MyBaseMapper
  not-empty: false
  identity: mysql